# Generated by Django 3.2.4 on 2021-07-13 15:54

from django.db import migrations, models
import django.db.models.deletion
import edumeet.modules


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='과목이름')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('type', models.IntegerField(choices=[(1, 'admin'), (2, 'teacher'), (3, 'student')], verbose_name='유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경일')),
                ('class_id', models.ForeignKey(db_column='class_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='edumeet.classinfo')),
                ('grade_id', models.ForeignKey(db_column='grade_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='edumeet.gradeinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_subject', models.ForeignKey(db_column='subject_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='edumeet.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edumeet.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edumeet.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=20, unique=True, verbose_name='login_id')),
                ('password', models.CharField(max_length=30, validators=[edumeet.modules.pass_validator], verbose_name='password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edumeet.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_time', models.IntegerField(choices=[(1, '09:00~09:45'), (2, '10:00~10:45'), (3, '11:00~11:45'), (4, '13:00~13:45'), (5, '14:00~14:45'), (6, '15:00~15:45')])),
                ('class_date', models.DateField()),
                ('class_id', models.ForeignKey(db_column='class_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.classinfo')),
                ('grade_id', models.ForeignKey(db_column='grade_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.gradeinfo')),
                ('subject_id', models.ForeignKey(db_column='subject_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.subject')),
                ('user_id', models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.user')),
            ],
        ),
    ]
