# Generated by Django 3.2.4 on 2021-07-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumeet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='class_date',
            field=models.DateTimeField(),
        ),
    ]
