# Generated by Django 3.2.4 on 2021-07-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edumeet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_time', models.IntegerField(choices=[(1, '9:00~9:45'), (2, '10:00~10:45'), (3, '11:00~11:45'), (4, '13:00~13:45'), (5, '14:00~14:45'), (6, '15:00~15:45')])),
                ('class_date', models.DateField()),
                ('subject_id', models.ForeignKey(db_column='subject_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.subject')),
                ('user_id', models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.user')),
            ],
        ),
    ]
