# Generated by Django 3.2.4 on 2021-07-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edumeet', '0002_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.classinfo'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='grade_id',
            field=models.ForeignKey(db_column='grade_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.gradeinfo'),
        ),
    ]
