# Generated by Django 3.2.4 on 2021-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edumeet', '0003_auto_20210712_2334'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classinfo',
            table='edumeet_classinfo',
        ),
        migrations.AlterModelTable(
            name='gradeinfo',
            table='edumeet_gradeinfo',
        ),
        migrations.AlterModelTable(
            name='lecture',
            table='edumeet_lecture',
        ),
        migrations.AlterModelTable(
            name='logininfo',
            table='edumeet_loginfo',
        ),
        migrations.AlterModelTable(
            name='studentuser',
            table='edumeet_studentuser',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='edumeet_subject',
        ),
        migrations.AlterModelTable(
            name='teacheruser',
            table='edumeet_teacheruser',
        ),
        migrations.AlterModelTable(
            name='user',
            table='edumeet_user',
        ),
    ]
