# Generated by Django 3.2.4 on 2021-07-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edumeet', '0004_auto_20210714_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lecture_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edumeet.lecture'),
        ),
    ]
