# Generated by Django 3.2.4 on 2021-07-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edumeet', '0005_alter_report_lecture_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='lecture_id',
            new_name='lecture',
        ),
    ]
