# Generated by Django 3.2.4 on 2021-07-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edumeet', '0006_rename_lecture_id_report_lecture'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='edumeet_report',
        ),
    ]
